### ISSUE TITLE
'shobjidl_core.h' file not found

### ISSUE THREAD

**Issue by ShaDow-Vip** [wangwenx190/qtacrylicmaterial#1]
Hello! I've been looking for a long time how to do such a thing, I came across your project. When I tried to run it, I got an error that I could not find two header files, I was looking for a solution to the problem, but I did not find it. 
![image](https://user-images.githubusercontent.com/44697703/118164129-8eb5ff80-b444-11eb-98a1-ec65bfe35599.png)

Qt 5.15.2 MinGW-64

C:\Users\Alexe\Documents\qtacrylicmaterial-main\src\utilities_win32.cpp:40: ошибка: shobjidl_core.h: No such file or directory
C:/Users/Alexe/Documents/qtacrylicmaterial-main/src/utilities_win32.cpp:40:10: fatal error: shobjidl_core.h: No such file or directory
 #include <shobjidl_core.h>
          ^~~~~~~~~~~~~~~~~

**Comment by wangwenx190** [comment]
It seems you are using MinGW to build this project. MinGW may miss some Windows SDK headers, you need to upgrade it to some recent version or switch to MSVC. But these solutions all need to recompile Qt, which may not be acceptable. For now, the temporary solution is comment out all these code that uses functions from these header files. For these functions, I've provided alternative ways such as reading from registry so the functionality may not be affected.

**Comment by ShaDow-Vip** [comment]
Thank you, switching to MSVC helped, but there is one problem. Around the window for some reason instead of the shadow blurring

![image](https://user-images.githubusercontent.com/44697703/118273548-e0629680-b4e5-11eb-9118-e0bfac4fb45e.png)

**Comment by ShaDow-Vip** [comment]
Also, is it possible to change the power of the blur?

**Comment by wangwenx190** [comment]
> 
> 
> Thank you, switching to MSVC helped, but there is one problem. Around the window for some reason instead of the shadow blurring
> 
> ![image](https://user-images.githubusercontent.com/44697703/118273548-e0629680-b4e5-11eb-9118-e0bfac4fb45e.png)

It's a drawback of the API I'm using. This issue only exists on Win10. Win7~Win8.1 doesn't have this issue. You can get rid of it by removing the window frame, such as enabling the `Qt::FramelessWindowHint` flag for the window.

**Comment by wangwenx190** [comment]
> 
> 
> Also, is it possible to change the power of the blur?

See this function:

https://github.com/wangwenx190/qtacrylicmaterial/blob/cbdbda18848b08da8437498493569803e82ab8be/src/utilities_win32.cpp#L115

Also this line:

https://github.com/wangwenx190/qtacrylicmaterial/blob/cbdbda18848b08da8437498493569803e82ab8be/src/qtacryliceffecthelper.cpp#L168

**Comment by ShaDow-Vip** [comment]
Thanks
