### ISSUE TITLE
Issues for a single application

### ISSUE THREAD

**Issue by ShaDow-Vip** [wangwenx190/qtacrylicmaterial#2]
Hello! You have closed issues in the single application project, so I write here) In the documentation you have written that you need to connect singleapplication.pri to the project, but this file is missing

**Comment by wangwenx190** [comment]
That repo was forked from someone else's repo. Originally it supports build with QMake, but I removed all Qmake project files long time ago and thus it now only supports build with CMake. All the documentation was written by the original author and I didn't touch it, so it may contains some outdated information. It needs some update indeed. BTW, I've enabled the issues function of that repo just now, sorry for the inconvenience.

**Comment by wangwenx190** [comment]
I closed this issue because it's not relevant to this repo. We can continue our discussion in that repo instead.
