### ISSUE TITLE
Windows 32-bit support? 

### ISSUE THREAD

**Issue by anjisZhou** [wangwenx190/qtacrylicmaterial#3]
I can't compile and pass in 32 bits, does it support it?

**Comment by wangwenx190** [comment]
1. It supports 32 bit in theory. What error did you get?
2. I will refactor this repo in some recent time, it's a huge refactoring, a completely rewrite. Currently the refactor is still work in progress

**Comment by anjisZhou** [comment]
![图片](https://user-images.githubusercontent.com/25604955/128459557-3299c64c-14d9-4855-afa7-b934f80db3a0.png)
这个错误

**Comment by anjisZhou** [comment]
找到问题了，是我编译的问题，不好意思

**Comment by wangwenx190** [comment]
这个项目马上就有很大的重构，重构规模相当于完全重写，建议先不要使用，等重构完成再使用。重构后亚克力效果好很多

**Comment by wangwenx190** [comment]
现在这个项目主要是模糊壁纸，重构后可以选择多个模式，还有自制的亚克力特效可选，模仿程度很高，几乎能以假乱真，而且还会添加Windows 11引入的MICA模式，这个MICA就是Win11版的亚克力，外观也很酷炫
